localConfigTemplatesPath: templates
trashRevision: 58a89d6dabe3e9b6f9754841ae95a1030c4d14ec

sonarr:
  marie:
    base_url: https://sonarr.marie.cologne
    api_key: !env MARIE_SONARR_API_KEY
    delete_unmanaged_custom_formats:
      enabled: true
    include:
      - template: sonarr-custom-formats
      - template: sonarr-quality
      - template: sonarr-original-language
      - template: sonarr-naming
    media_management:
      downloadPropersAndRepacks: doNotPrefer
  tobi:
    base_url: https://sonarr.wg.techtoto.dev
    api_key: !env TOBI_SONARR_API_KEY
    delete_unmanaged_custom_formats:
      enabled: true
    include:
      - template: sonarr-custom-formats
      - template: sonarr-quality
      - template: sonarr-original-language
      - template: sonarr-naming
    media_management:
      downloadPropersAndRepacks: doNotPrefer

radarr: {} # no radarr instance
